Add test for invalid @classDoc content
The test fails as it throws this exception when reporting the error.
```
java.lang.IllegalStateException: 2:11: Could not resolve 'test.Unknown' as could not find 'Unknown' in 'package test' [UnresolvedLink]
	at com.android.tools.metalava.model.source.doc.DocumentationIssueReporter$Companion$THROWING$1.report(DocumentationIssueReporter.kt:87)
```

It is due to the `DocumentationIssueReporter.THROWING` used in
`prepareForAppending(...)`. The follow-up change will fix it.

Bug: 447588621
Test: ./gradlew
Change-Id: I5558dfa0299a7568bb3ea09878a674c43433f37c